### ISSUE TITLE
FastMail Sync Issues

### ISSUE THREAD

**Issue by cooperpellaton** [nylas/N1#371]
I configured N1 with my main account: one from FastMail to which all of my domains are attached. All of my folders were successfully synced but no emails were. Using the search field, which I assume queries the server, also returns nothing. I'm at a loss. This combined with the fact that once the account details are put in they do not appear to be changeable leave me not understanding why the emails won't sync.

Could it be an issue at the TLD level where all of my emails from my domains that forward to my FastMail address are not being seen through the FastMail IMAP, or JMAP, implementation?

 No emails loaded throughout the entire application:
<img width="1552" alt="screen shot 2015-11-05 at 12 11 12 pm" src="https://cloud.githubusercontent.com/assets/5178017/10975833/cdc47f72-83b6-11e5-9659-2f0db736016a.png">

Lack of ability to change account details after setup:
<img width="632" alt="screen shot 2015-11-05 at 12 14 12 pm" src="https://cloud.githubusercontent.com/assets/5178017/10975843/d76252ac-83b6-11e5-9cb0-4802329d8464.png">
If you can change the above, then that UI paradigm is extremely flawed because I clicked in many places and scoured the settings to find nothing.

**Comment by mbilker** [comment]
Does FastMail use IMAP?

What is inside ~/Library/Application Support/Nylas N1/config.cson? You should be able to tweak some parameters in there. The lack of customization is due to the separation of the sync engine and the client.

**Comment by cooperpellaton** [comment]
FastMail is using a flavor of IMAP that is cleaned up JMAP and they are moving to full JMAP soon. I went to look for that config file to find nothing. This is the directory listing of that address.
![screen shot 2015-11-05 at 10 05 48 pm](https://cloud.githubusercontent.com/assets/5178017/10988326/6c64ab96-8409-11e5-9623-06424067cf96.png)

To note, the emails in the inbox did eventually load, as did the labels for my folders, but none of the contents of the folders every sync'd which makes no sense as IMAP/JMAP should permit that.

**Comment by mbilker** [comment]
ok. It's actually ~/.nylas/config.cson and beware it has personal information pertaining to account authentication with the sync engine server.

**Comment by cooperpellaton** [comment]
I've removed a lot of the private information so I can post the file below. As far as I can tell nothing looks out of the ordinary. I'll take a look at the sync engine tomorrow and try and see if it has something to do with the way the folder contents is being parsed/dataset being handled separately from that of the inbox.

```
"*":
  core:
    disabledPackages: [
      "calendar-bar"
    ]
    workspace:
      mode: "split"
      hiddenLocations:
        MessageListSidebar:
          id: "MessageListSidebar"
          Toolbar:
            id: "MessageListSidebar:Toolbar"
  updateLevel: "patch"
  env: "production"
  updateIdentity: "d0522bc6-3e49-4cf2-a519-ac7f7e497f26"
  invitationCode: "c7332caed3224c69a08801e6d8326b88"
  nylas:
    accounts: [
      {
        client_id: removed
        server_id: removed
        object: "account"
        account_id: removed
        name: "Cooper Pellaton"
        provider: "custom"
        email_address: removed
        organization_unit: "folder"
        id: removed
      }
      {
        client_id: removed
        server_id: removed
        object: "account"
        account_id: removed
        name: "Cooper Pellaton"
        provider: "gmail"
        email_address: removed
        organization_unit: "label"
        id: removed
      }
      {
        client_id: removed
        server_id: removed
        object: "account"
        account_id: removed
        name: "Cooper Pellaton"
        provider: "gmail"
        email_address: removed
        organization_unit: "label"
        id: removed
      }
      {
        client_id: removed
        server_id: removed
        object: "account"
        account_id: removed
        name: "Cooper Pellaton"
        provider: "gmail"
        email_address: removed
        organization_unit: "label"
        id:
      }
    ]
    currentAccountIndex: 0
    accountTokens:
      removed
    mailto:
      "prompted-about-default": true
    "44t5gr8ao4gf0y286xwywnjyd":
      cursor: "bu8k1qvcnmpb7gvvmulhgev22"
    e1ge413wk7oqow0ri7u52gfph:
      cursor: "41yw1afg9fhx0qhx4i76w69j1"
    "9evchn1ptla7wak5szxfaiqhf":
      cursor: "88x0vdjn174a06e4xa1mlu0yw"
```
